version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # Tag the image with the Jenkins BUILD_NUMBER env var
    image: getting-started-app:${BUILD_NUMBER}
    # We don't map host ports here; NGINX will do the routing
    expose:
      - "3000"

  nginx:
    # Pull the official NGINX Alpine image—no host install needed
    image: nginx:alpine
    ports:
      - "3000:80"      # Expose container port 80 on host 3000
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
